<$PLAN9/src/mkhdr

BIN=$PREFIX/bin

TARG=glendy
OFILES=\
	glendy.$O\

CFLAGS=$CFLAGS -D'FACE_DIR="'$FACE_DIR'"'

pre-install:V:
	mkdir -p $BIN

install:V: pre-install $TARG.install

<$PLAN9/src/mkone
