9 ?= 9
MK ?= ${9} mk

PREFIX ?= /usr
FACE_DIR ?= ${PREFIX}/share/face
export PREFIX := ${PREFIX}
export FACE_DIR := ${FACE_DIR}

.PHONY: all
all:
	${MK} all

.PHONY: clean
clean:
	${MK} clean

.PHONY: install
install:
	${MK} install

.PHONY: nuke
nuke:
	${MK} nuke