9 ?= 9
MK ?= ${9} mk

PREFIX ?= /usr
export PREFIX := ${PREFIX}

.PHONY: all
all:
	${MK} all

.PHONY: clean
clean:
	${MK} clean

.PHONY: install
install:
	${MK} install

.PHONY: nuke
nuke:
	${MK} nuke